name: housing_risk_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.0
  - numpy>=1.24
  - matplotlib>=3.7
  - geopandas>=0.14
  - seaborn>=0.12
  - shapely>=2.0
  - altair>=4.0
  - vl-convert-python>=1.0
  - streamlit>=1.28
  - pydeck>=0.8
  - pathlib2>=2.3